project:
  type: website
  output-dir: _site
website:
  title: "Penguin Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Analysis
format:
  html:
    theme: [cosmo, brand]
